### ISSUE TITLE
The scout2.0 doesn't move in RVIZ

### ISSUE THREAD

**Issue by gzc1021** [agilexrobotics/ugv_gazebo_sim#13]
I followed the steps here https://github.com/agilexrobotics/ugv_gazebo_sim/tree/master/scout and run 
roslaunch scout_gazebo_sim scout_empty_world.launch
the model displays normally in gazebo and RVIZ.
When I run
rosrun teleop_twist_keyboard teleop_twist_keyboard.py 
the model can move normally in gazebo,but only the wheels rotate and the car doesn't move  in RVIZ.
The screenshot is the result when I run roslaunch scout_gazebo_sim scout_empty_world.launch,and the video is the problem I described above.

https://user-images.githubusercontent.com/62643094/155087240-42310d62-9f09-46cd-b21e-2a93c2cd3767.mp4

![screenshot](https://user-images.githubusercontent.com/62643094/155087299-e7dc8934-3b6c-4b0c-9a32-960fcf2bbac5.png)

**Comment by JinchuanMa** [comment]
> hi, did you fix this problem? I also encounter this problem, and scout2.0 vehicle keeps sliding left slightly, it also oscillates up and down when it is staying still
> 
> 请问这个问题您解决了吗？而且，这车不仅在rviz里不移动，而且还会滑移，静止的时候还会振动，这些问题您有遇到过吗？

请问你解决这个问题了吗？scout mini在仿真环境会抖动。
