### ISSUE TITLE
readme error

### ISSUE THREAD

**Issue by mengchaoheng** [agilexrobotics/ugv_gazebo_sim#14]
git clone https://github.com/agilexrobotics/ugv_sim/hunter.git ???

**Comment by mengchaoheng** [comment]
and have a error:

```Console
parallels@ubuntu-linux-20-04-desktop:~/hunter_ws$ roslaunch hunter2_gazebo hunter2_gazebo.launch
... logging to /home/parallels/.ros/log/bbaa9e3a-b0ea-11ec-a241-852e8e8269b4/roslaunch-ubuntu-linux-20-04-desktop-743149.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu-linux-20-04-desktop:42069/

SUMMARY
========

PARAMETERS
 * /ackermann_steering_controller/allow_multiple_cmd_vel_publishers: True
 * /ackermann_steering_controller/angular/z/has_acceleration_limits: True
 * /ackermann_steering_controller/angular/z/has_velocity_limits: True
 * /ackermann_steering_controller/angular/z/max_acceleration: 3.0
 * /ackermann_steering_controller/angular/z/max_velocity: 3.0
 * /ackermann_steering_controller/base_frame_id: base_link
 * /ackermann_steering_controller/enable_odom_tf: True
 * /ackermann_steering_controller/estimate_velocity_from_position: True
 * /ackermann_steering_controller/front_steer: front_steer_joint
 * /ackermann_steering_controller/linear/x/has_acceleration_limits: True
 * /ackermann_steering_controller/linear/x/has_velocity_limits: True
 * /ackermann_steering_controller/linear/x/max_acceleration: 2.0
 * /ackermann_steering_controller/linear/x/max_velocity: 10.0
 * /ackermann_steering_controller/odom_frame_id: /ackermann_steeri...
 * /ackermann_steering_controller/open_loop: False
 * /ackermann_steering_controller/pose_covariance_diagonal: [0.001, 0.001, 0....
 * /ackermann_steering_controller/publish_cmd: True
 * /ackermann_steering_controller/publish_rate: 5
 * /ackermann_steering_controller/rear_wheel: rear_wheel_joint
 * /ackermann_steering_controller/steer_pos_multiplier: 1.0
 * /ackermann_steering_controller/twist_covariance_diagonal: [0.001, 0.001, 0....
 * /ackermann_steering_controller/type: ackermann_steerin...
 * /ackermann_steering_controller/wheel_radius: 0.1
 * /ackermann_steering_controller/wheel_radius_multiplier: 1.0
 * /ackermann_steering_controller/wheel_separation_h: 0.60986
 * /ackermann_steering_controller/wheel_separation_h_multiplier: 1.0
 * /front_steer_left_joint_position_controller/joint: front_steer_left_...
 * /front_steer_left_joint_position_controller/pid/d: 0
 * /front_steer_left_joint_position_controller/pid/i: 10
 * /front_steer_left_joint_position_controller/pid/i_clamp: 100
 * /front_steer_left_joint_position_controller/pid/p: 100
 * /front_steer_left_joint_position_controller/type: position_controll...
 * /gains/left_rear_joint/d: 10.0
 * /gains/left_rear_joint/i: 0.5
 * /gains/left_rear_joint/i_clamp: 3.0
 * /gains/left_rear_joint/p: 100000.0
 * /gains/right_rear_joint/d: 10.0
 * /gains/right_rear_joint/i: 0.5
 * /gains/right_rear_joint/i_clamp: 3.0
 * /gains/right_rear_joint/p: 100000.0
 * /gazebo/enable_ros_network: True
 * /joint_state_publisher/publish_rate: 100
 * /joint_state_publisher/type: joint_state_contr...
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 50.0
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /rqt_robot_steering/default_topic: ackermann_steerin...
 * /rqt_robot_steering/default_vw_max: 0.69
 * /rqt_robot_steering/default_vw_min: -0.69
 * /rqt_robot_steering/default_vx_max: 1.0
 * /rqt_robot_steering/default_vx_min: -1.0
 * /steer_bot_hardware_gazebo/enable_ackermann_link: True
 * /steer_bot_hardware_gazebo/front_steer: front_steer_joint
 * /steer_bot_hardware_gazebo/rear_wheel: rear_wheel_joint
 * /steer_bot_hardware_gazebo/virtual_front_steers: ['front_steer_lef...
 * /steer_bot_hardware_gazebo/virtual_front_wheels: ['front_left_whee...
 * /steer_bot_hardware_gazebo/virtual_rear_wheels: ['left_rear_joint...
 * /steer_bot_hardware_gazebo/wheel_separation_h: 0.60986
 * /steer_bot_hardware_gazebo/wheel_separation_w: 0.47
 * /use_sim_time: True

NODES
  /
    controller_spawner (controller_manager/spawner)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    hunter_spawn (gazebo_ros/spawn_model)
    robot_state_publisher (robot_state_publisher/state_publisher)
    rqt_robot_steering (rqt_robot_steering/rqt_robot_steering)

auto-starting new master
process[master]: started with pid [743166]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to bbaa9e3a-b0ea-11ec-a241-852e8e8269b4
process[rosout-1]: started with pid [743186]
started core service [/rosout]
process[gazebo-2]: started with pid [743193]
process[gazebo_gui-3]: started with pid [743196]
process[controller_spawner-4]: started with pid [743201]
ERROR: cannot launch node of type [robot_state_publisher/state_publisher]: Cannot locate node of type [state_publisher] in package [robot_state_publisher]. Make sure file exists in package path and permission is set to executable (chmod +x)
process[rqt_robot_steering-6]: started with pid [743204]
process[hunter_spawn-7]: started with pid [743205]
[INFO] [1648728276.674664, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1648728276.683518, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1648728276.685617, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1648728276.761262284]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1648728276.761946456]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1648728276.823551538]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1648728276.824460906]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[WARN] [1648728306.797808, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[controller_spawner-4] process has finished cleanly
log file: /home/parallels/.ros/log/bbaa9e3a-b0ea-11ec-a241-852e8e8269b4/controller_spawner-4*.log


```

**Comment by dashun1234** [comment]
git clone https://github.com/agilexrobotics/ugv_gazebo_sim.git

**Comment by mengchaoheng** [comment]
> and have a error:
> 
> ```
> parallels@ubuntu-linux-20-04-desktop:~/hunter_ws$ roslaunch hunter2_gazebo hunter2_gazebo.launch
> ... logging to /home/parallels/.ros/log/bbaa9e3a-b0ea-11ec-a241-852e8e8269b4/roslaunch-ubuntu-linux-20-04-desktop-743149.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://ubuntu-linux-20-04-desktop:42069/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /ackermann_steering_controller/allow_multiple_cmd_vel_publishers: True
>  * /ackermann_steering_controller/angular/z/has_acceleration_limits: True
>  * /ackermann_steering_controller/angular/z/has_velocity_limits: True
>  * /ackermann_steering_controller/angular/z/max_acceleration: 3.0
>  * /ackermann_steering_controller/angular/z/max_velocity: 3.0
>  * /ackermann_steering_controller/base_frame_id: base_link
>  * /ackermann_steering_controller/enable_odom_tf: True
>  * /ackermann_steering_controller/estimate_velocity_from_position: True
>  * /ackermann_steering_controller/front_steer: front_steer_joint
>  * /ackermann_steering_controller/linear/x/has_acceleration_limits: True
>  * /ackermann_steering_controller/linear/x/has_velocity_limits: True
>  * /ackermann_steering_controller/linear/x/max_acceleration: 2.0
>  * /ackermann_steering_controller/linear/x/max_velocity: 10.0
>  * /ackermann_steering_controller/odom_frame_id: /ackermann_steeri...
>  * /ackermann_steering_controller/open_loop: False
>  * /ackermann_steering_controller/pose_covariance_diagonal: [0.001, 0.001, 0....
>  * /ackermann_steering_controller/publish_cmd: True
>  * /ackermann_steering_controller/publish_rate: 5
>  * /ackermann_steering_controller/rear_wheel: rear_wheel_joint
>  * /ackermann_steering_controller/steer_pos_multiplier: 1.0
>  * /ackermann_steering_controller/twist_covariance_diagonal: [0.001, 0.001, 0....
>  * /ackermann_steering_controller/type: ackermann_steerin...
>  * /ackermann_steering_controller/wheel_radius: 0.1
>  * /ackermann_steering_controller/wheel_radius_multiplier: 1.0
>  * /ackermann_steering_controller/wheel_separation_h: 0.60986
>  * /ackermann_steering_controller/wheel_separation_h_multiplier: 1.0
>  * /front_steer_left_joint_position_controller/joint: front_steer_left_...
>  * /front_steer_left_joint_position_controller/pid/d: 0
>  * /front_steer_left_joint_position_controller/pid/i: 10
>  * /front_steer_left_joint_position_controller/pid/i_clamp: 100
>  * /front_steer_left_joint_position_controller/pid/p: 100
>  * /front_steer_left_joint_position_controller/type: position_controll...
>  * /gains/left_rear_joint/d: 10.0
>  * /gains/left_rear_joint/i: 0.5
>  * /gains/left_rear_joint/i_clamp: 3.0
>  * /gains/left_rear_joint/p: 100000.0
>  * /gains/right_rear_joint/d: 10.0
>  * /gains/right_rear_joint/i: 0.5
>  * /gains/right_rear_joint/i_clamp: 3.0
>  * /gains/right_rear_joint/p: 100000.0
>  * /gazebo/enable_ros_network: True
>  * /joint_state_publisher/publish_rate: 100
>  * /joint_state_publisher/type: joint_state_contr...
>  * /robot_description: <?xml version="1....
>  * /robot_state_publisher/publish_frequency: 50.0
>  * /rosdistro: noetic
>  * /rosversion: 1.15.14
>  * /rqt_robot_steering/default_topic: ackermann_steerin...
>  * /rqt_robot_steering/default_vw_max: 0.69
>  * /rqt_robot_steering/default_vw_min: -0.69
>  * /rqt_robot_steering/default_vx_max: 1.0
>  * /rqt_robot_steering/default_vx_min: -1.0
>  * /steer_bot_hardware_gazebo/enable_ackermann_link: True
>  * /steer_bot_hardware_gazebo/front_steer: front_steer_joint
>  * /steer_bot_hardware_gazebo/rear_wheel: rear_wheel_joint
>  * /steer_bot_hardware_gazebo/virtual_front_steers: ['front_steer_lef...
>  * /steer_bot_hardware_gazebo/virtual_front_wheels: ['front_left_whee...
>  * /steer_bot_hardware_gazebo/virtual_rear_wheels: ['left_rear_joint...
>  * /steer_bot_hardware_gazebo/wheel_separation_h: 0.60986
>  * /steer_bot_hardware_gazebo/wheel_separation_w: 0.47
>  * /use_sim_time: True
> 
> NODES
>   /
>     controller_spawner (controller_manager/spawner)
>     gazebo (gazebo_ros/gzserver)
>     gazebo_gui (gazebo_ros/gzclient)
>     hunter_spawn (gazebo_ros/spawn_model)
>     robot_state_publisher (robot_state_publisher/state_publisher)
>     rqt_robot_steering (rqt_robot_steering/rqt_robot_steering)
> 
> auto-starting new master
> process[master]: started with pid [743166]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to bbaa9e3a-b0ea-11ec-a241-852e8e8269b4
> process[rosout-1]: started with pid [743186]
> started core service [/rosout]
> process[gazebo-2]: started with pid [743193]
> process[gazebo_gui-3]: started with pid [743196]
> process[controller_spawner-4]: started with pid [743201]
> ERROR: cannot launch node of type [robot_state_publisher/state_publisher]: Cannot locate node of type [state_publisher] in package [robot_state_publisher]. Make sure file exists in package path and permission is set to executable (chmod +x)
> process[rqt_robot_steering-6]: started with pid [743204]
> process[hunter_spawn-7]: started with pid [743205]
> [INFO] [1648728276.674664, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
> [INFO] [1648728276.683518, 0.000000]: Loading model XML from ros parameter robot_description
> [INFO] [1648728276.685617, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
> [ INFO] [1648728276.761262284]: Finished loading Gazebo ROS API Plugin.
> [ INFO] [1648728276.761946456]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
> [ INFO] [1648728276.823551538]: Finished loading Gazebo ROS API Plugin.
> [ INFO] [1648728276.824460906]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
> [WARN] [1648728306.797808, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
> [controller_spawner-4] process has finished cleanly
> log file: /home/parallels/.ros/log/bbaa9e3a-b0ea-11ec-a241-852e8e8269b4/controller_spawner-4*.log
> ```

@dashun1234

**Comment by mengchaoheng** [comment]
```
ERROR: cannot launch node of type [robot_state_publisher/state_publisher]: Cannot locate node of type [state_publisher] in package [robot_state_publisher]. Make sure file exists in package path and permission is set to executable (chmod +x)
process[rqt_robot_steering-6]: started with pid [743204]
```
@dashun1234

**Comment by dashun1234** [comment]
@mengchaoheng  Source your workspace with this command：source devel/setup.bash

**Comment by mengchaoheng** [comment]
> @mengchaoheng Source your workspace with this command：source devel/setup.bash

It doesn't work

**Comment by mengchaoheng** [comment]
I have fix it! see [answer](https://answers.ros.org/question/357672/cannot-locate-node-of-type-state_publisher/). The 15th code of file "ugv_gazebo_sim/hunter/hunter2_control/launch/hunter2_v_contol.launch" need to change to :
```
<node name="robot_state_publisher" pkg="robot_state_publisher" type="robot_state_publisher" >
```
