### ISSUE TITLE
Orientation issue of the Hunter URDF

### ISSUE THREAD

**Issue by AntoineVi** [agilexrobotics/ugv_gazebo_sim#2]
Hello ! 
I'm currently working with your Hunter 2 mobile base and I think there is a problem with the orientation of the Hunter 2 mesh/URDF. 
Indeed, the forward axis is the Y one but usually it's the X one instead (see picture below). Consequently, I have some issues with the consistency between Gazebo and RVIZ  such as odometry computation on RVIZ. 
I tried to rotate the URDF file around the Z axis but it reverses the left/right rotations with the Ackermann-ros-controller.

Did I make a mistake somewhere ? Otherwise, could you add/update the Hunter 2 mesh/URDF please ?

Best regards.

![hunter_axis_issue](https://user-images.githubusercontent.com/34862129/137520489-a3e9879d-4010-4c87-ab19-062ee52d5fb3.png)

**Comment by agilexrobotics** [comment]
Hello, thank you for your question
I've corrected that, and now Hunter's X-axis is forward

Best regards！
