### ISSUE TITLE
Question about removal of ranger_mini

### ISSUE THREAD

**Issue by madjxatw** [agilexrobotics/ugv_gazebo_sim#22]
Not a bug, but just wonder why ranger_mini got removed from the repo? Any special reason?

**Comment by smalleha** [comment]
Are you referring to the Ranger Mini v1? It seems that this model has been discontinued.

**Comment by madjxatw** [comment]
> Are you referring to the Ranger Mini v1? It seems that this model has been discontinued.

So there is no where for Ranger Mini v1 users to get the gazebo sim files?

**Comment by lagrangeluo** [comment]
> > Are you referring to the Ranger Mini v1? It seems that this model has been discontinued.
> 
> So there is no where for Ranger Mini v1 users to get the gazebo sim files?

You can find ranger mini v1 in branch old_version
