### ISSUE TITLE
 Is ranger_mini_v2 ranger_basegoing to be added?

### ISSUE THREAD

**Issue by eleven110** [agilexrobotics/ugv_gazebo_sim#25]

**Comment by eleven110** [comment]
<link name="base_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0"/>
            <mass value="10"/>
            <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="1.57 0 3.14 " />
            <geometry>
                <mesh filename="package://ranger_mini_v2/meshes/ranger_base.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 -0.1" rpy="0 0 0" />
            <geometry>
                <box size="0.5 0.35 0.2"/>
            </geometry>
        </collision>
 
    </link>

the new ranger_mini_v2 ranger_base.dae file，cannot load in the ranger_mini_gazebo.xacro file。
![微信截图_20240126190352](https://github.com/agilexrobotics/ugv_gazebo_sim/assets/85616395/b23fc721-ab4d-40bf-9f5b-68b1d1d5b7f3)

**Comment by acachathuranga** [comment]
The ranger_base.dae file is included using git lfs. However, when trying to download the file, it still throws the following error.

`This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/agilexrobotics/ugv_gazebo_sim.git/info/lfs'`

Any support or else alternative download link for the ranger_base.dae is appreciated!

**Comment by james-yoo** [comment]
Any update regarding this issue?

**Comment by smalleha** [comment]
ranger_base has been uploaded in ranger_mini_V2/ranger_mini_v2/meshes/ranger_base.zip; Need to decompress before use
