### ISSUE TITLE
I want to run the file roslaunch hunter2_gazebo hunter2_gazebo.launch. BUT Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by sdk17586** [agilexrobotics/ugv_gazebo_sim#26]
I want to run the file roslaunch hunter2_gazebo hunter2_gazebo.launch. However, I encounter the following error message. What should I do?

[ WARN] [1711952264.279188363]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1711952264.625389479]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1711952264.633736037]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[INFO] [1711952264.636500, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1711952264.695039022]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1711952264.696363759]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[INFO] [1711952265.005902, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1711952265.009533, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1711952266.819356, 0.000000]: Calling service /gazebo/spawn_urdf_model
Segmentation fault (core dumped)
Service call failed: unable to connect to service: [Errno 104] Connection reset by peer
[ERROR] [1711952267.888056, 0.000000]: Spawn service failed. Exiting.
[gazebo-2] process has died [pid 5196, exit code 139, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -e ode /home/rdv/hunter_ws/src/ugv_sim/hunter/hunter2_gazebo/world/house.world __name:=gazebo __log:=/home/rdv/.ros/log/8cfc836e-efef-11ee-a193-48210b336f4a/gazebo-2.log].
log file: /home/rdv/.ros/log/8cfc836e-efef-11ee-a193-48210b336f4a/gazebo-2*.log
[hunter_spawn-7] process has died [pid 5209, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -urdf -param robot_description -model hunter2_base -z 0.05 __name:=hunter_spawn __log:=/home/rdv/.ros/log/8cfc836e-efef-11ee-a193-48210b336f4a/hunter_spawn-7.log].
log file: /home/rdv/.ros/log/8cfc836e-efef-11ee-a193-48210b336f4a/hunter_spawn-7*.log

![image](https://github.com/agilexrobotics/ugv_gazebo_sim/assets/122353362/399155d5-14d7-41fd-a6e3-92d17bae2871)

**Comment by UsamaHamayun1** [comment]
hello , 

i am getting the same issue for launching hunter2_gazebo.launch , Rest is working 

* /steer_bot_hardware_gazebo/enable_ackermann_link: True
 * /steer_bot_hardware_gazebo/front_steer: front_steer_joint
 * /steer_bot_hardware_gazebo/rear_wheel: rear_wheel_joint
 * /steer_bot_hardware_gazebo/virtual_front_steers: ['front_steer_lef...
 * /steer_bot_hardware_gazebo/virtual_front_wheels: ['front_left_whee...
 * /steer_bot_hardware_gazebo/virtual_rear_wheels: ['left_rear_joint...
 * /steer_bot_hardware_gazebo/wheel_separation_h: 0.60986
 * /steer_bot_hardware_gazebo/wheel_separation_w: 0.47
 * /use_sim_time: True

NODES
  /
    controller_spawner (controller_manager/spawner)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    hunter_spawn (gazebo_ros/spawn_model)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rqt_robot_steering (rqt_robot_steering/rqt_robot_steering)

ROS_MASTER_URI=http://localhost:11311

process[gazebo-1]: started with pid [4143]
process[gazebo_gui-2]: started with pid [4148]
process[controller_spawner-3]: started with pid [4153]
process[robot_state_publisher-4]: started with pid [4154]
process[rqt_robot_steering-5]: started with pid [4155]
process[hunter_spawn-6]: started with pid [4156]
[ WARN] [1712934201.013413138]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1712934201.211284909]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1712934201.212040564]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1712934201.235491797]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1712934201.236202081]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[INFO] [1712934201.265182, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1712934201.500831, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1712934201.504439, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1712934201.806999, 0.000000]: Calling service /gazebo/spawn_urdf_model
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
Segmentation fault (core dumped)
Service call failed: unable to connect to service: [Errno 104] Connection reset by peer
[ERROR] [1712934202.654896, 0.000000]: Spawn service failed. Exiting.
[gazebo-1] process has died [pid 4143, exit code 139, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -e ode /home/usama/hunter_ws/src/ugv_sim/hunter/hunter2_gazebo/world/house.world __name:=gazebo __log:=/home/usama/.ros/log/69ee5f5e-f8dd-11ee-882c-70d82325a8aa/gazebo-1.log].
log file: /home/usama/.ros/log/69ee5f5e-f8dd-11ee-882c-70d82325a8aa/gazebo-1*.log
[hunter_spawn-6] process has died [pid 4156, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -urdf -param robot_description -model hunter2_base -z 0.05 __name:=hunter_spawn __log:=/home/usama/.ros/log/69ee5f5e-f8dd-11ee-882c-70d82325a8aa/hunter_spawn-6.log].
log file: /home/usama/.ros/log/69ee5f5e-f8dd-11ee-882c-70d82325a8aa/hunter_spawn-6*.log
[WARN] [1712934231.442916, 0

**Comment by charon-cheung** [comment]
here is mine
```
[ INFO] [1713528394.406269380]: waitForService: Service [/gazebo/set_physics_properties] is now available.
Service call failed: transport error completing service call: unable to receive data from sender, check sender's logs for details
[ERROR] [1713528398.036492, 0.000000]: Spawn service failed. Exiting.
Segmentation fault (core dumped)
[gazebo-1] process has died [pid 19074, exit code 139
```
