### ISSUE TITLE
Lack of controller for hunter_se in humble environment

### ISSUE THREAD

**Issue by TZECHIN6** [agilexrobotics/ugv_gazebo_sim#28]
How can I control the hunter_se in humble and gazebo? The current project is missing `hunter_se_control`...

Please advise great thanks.

**Comment by smalleha** [comment]
Hello, the readme about hunter_se has been uploaded. Can you run hunter_se in gazebo according to the readme

**Comment by TZECHIN6** [comment]
@smalleha hi, would you mind pointing me where to find the new update? as the commit in humble is still 4d64ff2 which was two weeks ago.

Besides that, I would also want to know will the hunter_se controller be uploaded, currently its missing...

Thanks for your work.

**Comment by TZECHIN6** [comment]
I found the gazebo controller plugin is included, and `cmd_vel` topic is available.
