### ISSUE TITLE
bunker no cmd_vel

### ISSUE THREAD

**Issue by khuechuong** [agilexrobotics/ugv_gazebo_sim#32]
I ran bunker gazebo command
```
roslaunch bunker_gazebo_sim bunker_gazebo_sim.launch 
```
but rostopic list doesn't show cmd_vel so I can't control its movements.

**Comment by lagrangeluo** [comment]
You can have a look of your terminal if there are some errors like missing controller,maybe you miss some dependencies because in my computer everything is running well

**Comment by khuechuong** [comment]
There are no errors in terminal. I have ros noetic.
